=== michaelpanorios/ebookshop-data-handling/online_bookshop_new.dtd
<!ELEMENT online_bookshop (author_list,Book_categories,Book_secondary_categories+,book_list,contact_details)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author_list (author+)>
<!ELEMENT author EMPTY>
<!ELEMENT Book_categories (book_category*)>
<!ELEMENT book_category (#PCDATA)>
<!ELEMENT Book_secondary_categories (secondary_category*)>
<!ELEMENT secondary_category (#PCDATA)>
<!ELEMENT book_list (book+)>
<!ELEMENT book (book_titles_info,authors,ISBN,book_descr,book_characteristics,cost_information,other_information)>
<!ELEMENT book_titles_info EMPTY>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT book_descr (review,for_ages*)>
<!ELEMENT review (#PCDATA)>
<!ELEMENT for_ages (#PCDATA)>
<!ELEMENT authors (other_partners)>
<!ELEMENT other_partners (illustration?,translation?)>
<!ELEMENT illustration (#PCDATA)>
<!ELEMENT translation (#PCDATA)>
<!ELEMENT book_characteristics (dimensions?,publisher,pages,weight?,language)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT dimensions (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT cost_information (start_value+,end_value+)>
<!ELEMENT start_value (#PCDATA)>
<!ELEMENT end_value (#PCDATA)>
<!ELEMENT other_information (availability)>
<!ELEMENT availability (#PCDATA)>
<!ELEMENT contact_details (address,tel*,email*)>
<!ELEMENT address ANY>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ATTLIST online_bookshop name CDATA #REQUIRED free_ship CDATA #IMPLIED>
<!ATTLIST availability send CDATA #IMPLIED>
<!ATTLIST start_value currency CDATA #FIXED "euro">
<!ATTLIST end_value currency CDATA #FIXED "euro" percent_of_discount CDATA #IMPLIED with_discount (yes|no) "no">
<!ATTLIST weight w_unit (pounds|gr) "gr">
<!ATTLIST publisher publisher_year  CDATA #REQUIRED publisher_country  CDATA #IMPLIED>
<!ATTLIST dimensions unit CDATA #FIXED "cm">
<!ATTLIST secondary_category sub_cat ID #REQUIRED category_id IDREF #REQUIRED>
<!ATTLIST author auid ID #REQUIRED name CDATA #REQUIRED>
<!ATTLIST book_category category_id ID #REQUIRED>
<!ATTLIST book book_id ID #REQUIRED category_id IDREF #REQUIRED sub_cat IDREF #REQUIRED publish CDATA #IMPLIED>
<!ATTLIST authors author_id ID #REQUIRED>
<!ATTLIST book_titles_info title CDATA #REQUIRED subtitle CDATA #IMPLIED>

=== michaelpanorios/ebookshop-data-handling/online_bookshop_new.xml
<?xml version = "1.0"  encoding = "utf-8"?>
<!DOCTYPE online_bookshop SYSTEM "online_bookshop_new.dtd"> 
<?xml-stylesheet href="bookshop.css" type="text/css"?>

<online_bookshop name="XYZ ONLINE BOOKSHOP" free_ship="Δωρεάν μεταφορικά σε παραγγελίες βιβλίων από 14,50€">
    <author_list>
        <author auid="_1" name="Tolstoi Leon"/>
        <author auid="_2" name="Fischek Sebastian"/>
        <author auid="_3" name="Jo Nesbo" />
        <author auid="_4" name="ΕΥΣΤΑΘΙΟΥ ΕΥΑΓΓΕΛΙΑ" />
        <author auid="_5" name="Rafe Colburn" />
        <author auid="_6" name="Laura Lemay" />
        <author auid="_7" name="Jennifer Kyrnin" />
        <author auid="_8" name="Glass Russel" />
        <author auid="_9" name="Callahan Sean" />
        <author auid="_10" name="Petzold Charles" />
        <author auid="_11" name="ΜΠΑΜΠΕΤΑ ΙΩΑΝΝΑ" />
        <author auid="_12" name="ΕΞΥΠΕΡΙ ΑΝΤΟΥΑΝ ΝΤΕ ΣΑΙΝΤ" />
        <author auid="_13" name="ΜΑΝΔΗΛΑΡΑΣ ΦΙΛΙΠΠΟΣ" />
    </author_list>
    <Book_categories>
        <book_category category_id="_K1">Λογοτεχνία</book_category>
        <book_category category_id="_K2">Παιδικά</book_category>
        <book_category category_id="_K3">Επιστήμες</book_category>
        <book_category category_id="_K4">Παιδαγωγικά</book_category>
        <book_category category_id="_K5">Ποίηση</book_category>
        <book_category category_id="_K6">Φιλοσοφία</book_category>
    </Book_categories>
    <Book_secondary_categories>
        <secondary_category sub_cat="_S1" category_id="_K1" >Ελληνική Λογοτεχνία </secondary_category>
        <secondary_category sub_cat="_S2" category_id="_K1" >Ποίηση</secondary_category>
        <secondary_category sub_cat="_S3" category_id="_K1" >Αστυνομική Λογοτεχνία</secondary_category>
        <secondary_category sub_cat="_S4" category_id="_K1" >Παγκόσμια Λογοτεχνία</secondary_category>
        <secondary_category sub_cat="_S5" category_id="_K1" >Παιδική Λογοτεχνία</secondary_category>
        <secondary_category sub_cat="_S6" category_id="_K2" >Παραμύθια</secondary_category>
        <secondary_category sub_cat="_S7" category_id="_K2" >Δραστηριότητες</secondary_category>
        <secondary_category sub_cat="_S8" category_id="_K2" >Προσχολική Ηλικία </secondary_category>
        <secondary_category sub_cat="_S9" category_id="_K2" >Πάνινα Βιβλία</secondary_category>
        <secondary_category sub_cat="_S10" category_id="_K2" >Εκπαιδευτικά Βιβλία</secondary_category>
        <secondary_category sub_cat="_S11" category_id="_K2" >Μυθολογία</secondary_category>
        <secondary_category sub_cat="_S12" category_id="_K2" >Εγκυκλοπαιδικά Βιβλία </secondary_category>
        <secondary_category sub_cat="_S13" category_id="_K3" >Οικονομία</secondary_category>
        <secondary_category sub_cat="_S14" category_id="_K3" >Ιατρική</secondary_category>
        <secondary_category sub_cat="_S15" category_id="_K3" >Μαθηματικά</secondary_category>
        <secondary_category sub_cat="_S16" category_id="_K3" >Πληροφορική</secondary_category>
        <secondary_category sub_cat="_S17" category_id="_K3" >Ιστορία</secondary_category>
        <secondary_category sub_cat="_S18" category_id="_K3" >Αρχιτεκτονική</secondary_category>
        <secondary_category sub_cat="_S19" category_id="_K3" >Πολιτικές Επιστήμες και Δίκαιο</secondary_category>
        <secondary_category sub_cat="_S20" category_id="_K3" >Βιολογία</secondary_category>
        <secondary_category sub_cat="_S21" category_id="_K3" >Ψυχολογία/Ψυχανάλυση</secondary_category>
        <secondary_category sub_cat="_S22" category_id="_K3" >Φυσική</secondary_category>
        <secondary_category sub_cat="_S23" category_id="_K3" >Χημεία</secondary_category>
        <secondary_category sub_cat="_S24" category_id="_K3" >Άλλες Επιστήμες</secondary_category>
        <secondary_category sub_cat="_S25" category_id="_K4" >Διδακτικές</secondary_category>
        <secondary_category sub_cat="_S26" category_id="_K4" >Παιδοψυχολογία</secondary_category>
        <secondary_category sub_cat="_S27" category_id="_K4" >Εκπαίδευση</secondary_category>
        <secondary_category sub_cat="_S28" category_id="_K4" >Παιδαγωγική</secondary_category>
        <secondary_category sub_cat="_S29" category_id="_K4" >Ειδική Αγωγή</secondary_category>
        <secondary_category sub_cat="_S30" category_id="_K5" >Ελληνική Ποίηση</secondary_category>
        <secondary_category sub_cat="_S31" category_id="_K5" >Παγκόσμια Ποίηση</secondary_category>
        <secondary_category sub_cat="_S32" category_id="_K6" >Αρχαία Ελληνική Φιλοσοφία</secondary_category>
        <secondary_category sub_cat="_S33" category_id="_K6" >Ιστορία Φιλοσοφίας</secondary_category>
        <secondary_category sub_cat="_S34" category_id="_K6" >Ανατολική Φιλοσοφία</secondary_category>
        <secondary_category sub_cat="_S35" category_id="_K6" >Φιλοσοφικά Δοκίμια</secondary_category>
        <secondary_category sub_cat="_S36" category_id="_K6" >Στοχασμοί</secondary_category>
    </Book_secondary_categories>
    
    <book_list>
        <book book_id="_no1" category_id="_K6" sub_cat="_S36">
            <book_titles_info title="Ημερολόγιο Σοφίας" />
            <authors author_id="_a1">
                <other_partners></other_partners>
            </authors>
            <ISBN>9789607408891</ISBN>
            <book_descr>
                <review>Το βιβλίο αυτό, έργο των τελευταίων χρόνων της ζωής του Τολστόι, είναι το βιβλίο που ο ίδιος θεωρούσε ως τη σημαντικότερη συνεισφορά του στην ανθρωπότητα. Μέσα σ' αυτό το απάνθισμα θρησκευτικών και φιλοσοφικών σκέψεων που ο Τολστόι άντλησε απ' τη παγκόσμια πνευματική κληρονομιά, μπορούμε να βρούμε κάποια λόγια που θα αγγίξουν τη ψυχή μας και θα μας φέρουν πιο κοντά στην ουσία των πραγμάτων</review>
            </book_descr>
            <book_characteristics>
                <dimensions unit="cm">14χ21</dimensions>
                <publisher publisher_year="2004">PRINTA</publisher>
                <pages>386</pages>
                <language>Ελληνικά</language>
            </book_characteristics>
            <cost_information>
                <start_value currency="euro">23,32</start_value>
                <end_value currency="euro" with_discount="yes" percent_of_discount="20%">18,66</end_value>
            </cost_information>
            <other_information>
                <availability send="Αποστολή 
                εντός 1-3 εργάσιμων ημερών.">Άμεσα διαθέσιμο</availability>
            </other_information>
        </book>

        <book book_id="_no2" category_id="_K1" sub_cat="_S3">
            <book_titles_info title="Το δέμα" />
            <authors author_id="_a2">
                <other_partners></other_partners>
            </authors>
            <ISBN>9789606054358</ISBN>
            <book_descr>
                <review>Τους τελευταίους μήνες, μετά το απαίσιο εκείνο γεγονός, μένεις κλεισμένη στο σπίτι σου. Θέλεις να το αφήσεις πίσω σου. Ένα πρωί, ο ταχυδρόμος σού αφήνει ένα δέμα για τον γείτονα που λείπει. Δεν έχεις ακούσει ποτέ ξανά το όνομά του. Κοιτάζεις από τον φράχτη, και ο κήπος του φαίνεται παρατημένος. Δείχνει σαν να μη ζει κάποιος εκεί καιρό τώρα. Κάτι σε σπρώχνει να ανοίξεις το δέμα.</review>
            </book_descr>
            <book_characteristics>
                <dimensions unit="cm">14χ21</dimensions>
                <publisher publisher_year="2018">ΔΙΟΠΤΡΑ</publisher>
                <pages>392</pages>
                <language>Ελληνικά</language>
            </book_characteristics>
            <cost_information>
                <start_value currency="euro">16,60</start_value>
                <end_value currency="euro" with_discount="yes" percent_of_discount="30%">11,60</end_value>
            </cost_information>
            <other_information>
                <availability send="Αποστολή 
                εντός 1-3 εργάσιμων ημερών.">Άμεσα διαθέσιμο</availability>
            </other_information>
        </book>

        <book book_id="_no3" category_id="_K1" sub_cat="_S3">
            <book_titles_info title="Το βασίλειο" subtitle="Δύο αδέλφια. Μία πόλη. Τα σκοτεινά μυστικά μιας ζωής" />
            <authors author_id="_a3">
                <other_partners></other_partners>
            </authors>
            <ISBN>9786180323054</ISBN>
            <book_descr>
                <review>ΠΑΝΤΑ ΤΟΝ ΠΡΟΣΤΑΤΕΥΕ. Από τα δεκάξι του, που χάθηκαν ξαφνικά οι γονείς τους, ο Ρόι ανέλαβε τη φροντίδα του μικρού του αδελφού, του Καρλ. Μεγαλώνοντας οι δρόμοι τους χωρίστηκαν. Ο Καρλ αποφάσισε να περιπλανηθεί στον κόσμο αναζητώντας μια καλύτερη τύχη. Ο Ρόι έμεινε πίσω, στο οικογενειακό κτήμα, στο απομονωμένο βασίλειό τους, ικανοποιημένος με μια ήσυχη καθημερινότητα. ΜΕΧΡΙ ΠΟΥ ΓΥΡΙΣΕ, ΓΙΑ ΝΑ ΔΙΕΚΔΙΚΗΣΕΙ ΜΙΑ ΘΕΣΗ ΣΤΟ ΒΑΣΙΛΕΙΟ… Χρόνια αργότερα, ο Καρλ επιστρέφει, με τη χαρισματική νέα του σύζυγο, την αρχιτέκτονα Σάνον. Έχουν ένα σωρό συναρπαστικά σχέδια – να χτίσουν ένα ξενοδοχείο στο κτήμα και να πνιγούν στα πλούτη τόσο τα αδέρφια όσο και όλο το χωριό. ΚΑΙ ΤΑ ΣΚΟΤΕΙΝΑ ΜΥΣΤΙΚΑ ΑΡΧΙΣΑΝ ΝΑ ΒΓΑΙΝΟΥΝ ΣΤΟ ΦΩΣ. Η χαρμόσυνη άφιξη σύντομα γίνεται η αφορμή για μια σειρά από γεγονότα που απειλούν ό,τι αγαπά και θέλει να διαφυλάξει ο Ρόι… Οικογενειακό χρέος, αναπάντεχες ανατροπές, όλο και περισσότερα πτώματα: ένα εκτυφλωτικό θρίλερ, ένα ακαταμάχητο αναγνωστικό κοκτέιλ.</review>
            </book_descr>
            <book_characteristics>
                <dimensions unit="cm">14χ21</dimensions>
                <publisher publisher_year="2020" publisher_country="GR">ΜΕΤΑΙΧΜΙΟ</publisher>
                <pages>696</pages>
                <language>Έλληνικα</language>
            </book_characteristics>
            <cost_information>
                <start_value currency="euro">19,90</start_value>
                <end_value currency="euro" with_discount="yes" percent_of_discount="10%">17,91</end_value>
            </cost_information>
            <other_information>
                <availability send="Αποστολή
